[build]
  # Directorio que contiene los archivos a desplegar
  publish = "dist"
  # Comando para instalar dependencias
  command = "npm install && npm run build"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18.16.0"
  # Versión de NPM
  NPM_VERSION = "9.5.1"
  # Variables de entorno
  NODE_ENV = "production"
  # Configuración de caché
  NETLIFY_USE_YARN = "true"
  YARN_FLAGS = "--cache-folder=.yarn-cache"

# Configuración de redirecciones
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Configuración de encabezados
[[headers]]
  # Aplicar estos encabezados a todas las rutas
  for = "/*"
  [headers.values]
    # Seguridad
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # CORS
    Access-Control-Allow-Origin = "*"
    # HSTS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # CSP (Content Security Policy)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https:;"

# Configuración de redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de encabezados de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Configuración de CORS
    Access-Control-Allow-Origin = "*"
    # HSTS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Configuración de encabezados de caché para activos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración de encabezados para archivos específicos
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=UTF-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json; charset=UTF-8"

# Configuración de redirecciones personalizadas
[[redirects]]
  from = "/blog/:year/:month/:day/:slug"
  to = "/blog/:slug"
  status = 301

# Configuración de funciones serverless (si es necesario)
[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Configuración de procesamiento de imágenes (si es necesario)
[images]
  compress = true
  fetch = true

# Configuración de compresión (si es necesario)
[build.processing]
  skip_processing = false

# Configuración de inyección de snippets (si es necesario)
[build.processing.html]
  pretty_urls = true

# Configuración de inyección de snippets (si es necesario)
[build.processing.css]
  bundle = true
  minify = true

# Configuración de inyección de snippets (si es necesario)
[build.processing.js]
  bundle = true
  minify = true

# Configuración de inyección de snippets (si es necesario)
[build.processing.images]
  compress = true

# Configuración de inyección de snippets (si es necesario)
[build.processing.skip_processing]
  paths = ["/admin/*", "/.netlify/*"]

# Configuración de inyección de snippets (si es necesario)
[build.processing.inline_config]
  enabled = true

# Configuración de inyección de snippets (si es necesario)
[build.processing.inline_config.rules]
  # Ejemplo de regla para inyección de snippets
  # "**/*.html" = "snippets/analytics.html"

# Configuración de inyección de snippets (si es necesario)
[build.processing.inline_config.variables]
  # Ejemplo de variables para inyección
  # SITE_URL = "https://reticulacreativa.com"
  # GA_TRACKING_ID = "UA-XXXXX-Y"

# Configuración de inyección de snippets (si es necesario)
[build.processing.inline_config.replacements]
  # Ejemplo de reemplazos
  # "{{SITE_URL}}" = "https://reticulacreativa.com"
  # "{{GA_TRACKING_ID}}" = "UA-XXXXX-Y"

# Configuración de inyección de snippets (si es necesario)
[build.processing.inline_config.files]
  # Ejemplo de archivos para inyección
  # "**/*.html" = "snippets/analytics.html"
